// Generated by gencpp from file deepracer_simulation_environment/GetWaypointSrv.msg
// DO NOT EDIT!


#ifndef DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_GETWAYPOINTSRV_H
#define DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_GETWAYPOINTSRV_H

#include <ros/service_traits.h>


#include <deepracer_simulation_environment/GetWaypointSrvRequest.h>
#include <deepracer_simulation_environment/GetWaypointSrvResponse.h>


namespace deepracer_simulation_environment
{

struct GetWaypointSrv
{

typedef GetWaypointSrvRequest Request;
typedef GetWaypointSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWaypointSrv
} // namespace deepracer_simulation_environment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepracer_simulation_environment::GetWaypointSrv > {
  static const char* value()
  {
    return "dd1c3c0f312afb554365a4b5e8f07a10";
  }

  static const char* value(const ::deepracer_simulation_environment::GetWaypointSrv&) { return value(); }
};

template<>
struct DataType< ::deepracer_simulation_environment::GetWaypointSrv > {
  static const char* value()
  {
    return "deepracer_simulation_environment/GetWaypointSrv";
  }

  static const char* value(const ::deepracer_simulation_environment::GetWaypointSrv&) { return value(); }
};


// service_traits::MD5Sum< ::deepracer_simulation_environment::GetWaypointSrvRequest> should match 
// service_traits::MD5Sum< ::deepracer_simulation_environment::GetWaypointSrv > 
template<>
struct MD5Sum< ::deepracer_simulation_environment::GetWaypointSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_simulation_environment::GetWaypointSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::GetWaypointSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_simulation_environment::GetWaypointSrvRequest> should match 
// service_traits::DataType< ::deepracer_simulation_environment::GetWaypointSrv > 
template<>
struct DataType< ::deepracer_simulation_environment::GetWaypointSrvRequest>
{
  static const char* value()
  {
    return DataType< ::deepracer_simulation_environment::GetWaypointSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::GetWaypointSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepracer_simulation_environment::GetWaypointSrvResponse> should match 
// service_traits::MD5Sum< ::deepracer_simulation_environment::GetWaypointSrv > 
template<>
struct MD5Sum< ::deepracer_simulation_environment::GetWaypointSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_simulation_environment::GetWaypointSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::GetWaypointSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_simulation_environment::GetWaypointSrvResponse> should match 
// service_traits::DataType< ::deepracer_simulation_environment::GetWaypointSrv > 
template<>
struct DataType< ::deepracer_simulation_environment::GetWaypointSrvResponse>
{
  static const char* value()
  {
    return DataType< ::deepracer_simulation_environment::GetWaypointSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::GetWaypointSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_GETWAYPOINTSRV_H
