// Generated by gencpp from file deepracer_simulation/ResetCarSrvRequest.msg
// DO NOT EDIT!


#ifndef DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_RESETCARSRVREQUEST_H
#define DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_RESETCARSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepracer_simulation
{
template <class ContainerAllocator>
struct ResetCarSrvRequest_
{
  typedef ResetCarSrvRequest_<ContainerAllocator> Type;

  ResetCarSrvRequest_()
    : ndist(0.0)
    , next_index(0)  {
    }
  ResetCarSrvRequest_(const ContainerAllocator& _alloc)
    : ndist(0.0)
    , next_index(0)  {
  (void)_alloc;
    }



   typedef float _ndist_type;
  _ndist_type ndist;

   typedef int32_t _next_index_type;
  _next_index_type next_index;





  typedef boost::shared_ptr< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetCarSrvRequest_

typedef ::deepracer_simulation::ResetCarSrvRequest_<std::allocator<void> > ResetCarSrvRequest;

typedef boost::shared_ptr< ::deepracer_simulation::ResetCarSrvRequest > ResetCarSrvRequestPtr;
typedef boost::shared_ptr< ::deepracer_simulation::ResetCarSrvRequest const> ResetCarSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace deepracer_simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eff28ed986b58db32d8bdead6e257efe";
  }

  static const char* value(const ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeff28ed986b58db3ULL;
  static const uint64_t static_value2 = 0x2d8bdead6e257efeULL;
};

template<class ContainerAllocator>
struct DataType< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepracer_simulation/ResetCarSrvRequest";
  }

  static const char* value(const ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 ndist\n\
int32 next_index\n\
";
  }

  static const char* value(const ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ndist);
      stream.next(m.next_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetCarSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepracer_simulation::ResetCarSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "ndist: ";
    Printer<float>::stream(s, indent + "  ", v.ndist);
    s << indent << "next_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.next_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_RESETCARSRVREQUEST_H
