// Generated by gencpp from file deepracer_simulation_environment/ResetCarSrv.msg
// DO NOT EDIT!


#ifndef DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_RESETCARSRV_H
#define DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_RESETCARSRV_H

#include <ros/service_traits.h>


#include <deepracer_simulation_environment/ResetCarSrvRequest.h>
#include <deepracer_simulation_environment/ResetCarSrvResponse.h>


namespace deepracer_simulation_environment
{

struct ResetCarSrv
{

typedef ResetCarSrvRequest Request;
typedef ResetCarSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetCarSrv
} // namespace deepracer_simulation_environment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepracer_simulation_environment::ResetCarSrv > {
  static const char* value()
  {
    return "51459ac9873b166b6314083bf1771edb";
  }

  static const char* value(const ::deepracer_simulation_environment::ResetCarSrv&) { return value(); }
};

template<>
struct DataType< ::deepracer_simulation_environment::ResetCarSrv > {
  static const char* value()
  {
    return "deepracer_simulation_environment/ResetCarSrv";
  }

  static const char* value(const ::deepracer_simulation_environment::ResetCarSrv&) { return value(); }
};


// service_traits::MD5Sum< ::deepracer_simulation_environment::ResetCarSrvRequest> should match 
// service_traits::MD5Sum< ::deepracer_simulation_environment::ResetCarSrv > 
template<>
struct MD5Sum< ::deepracer_simulation_environment::ResetCarSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_simulation_environment::ResetCarSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::ResetCarSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_simulation_environment::ResetCarSrvRequest> should match 
// service_traits::DataType< ::deepracer_simulation_environment::ResetCarSrv > 
template<>
struct DataType< ::deepracer_simulation_environment::ResetCarSrvRequest>
{
  static const char* value()
  {
    return DataType< ::deepracer_simulation_environment::ResetCarSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::ResetCarSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepracer_simulation_environment::ResetCarSrvResponse> should match 
// service_traits::MD5Sum< ::deepracer_simulation_environment::ResetCarSrv > 
template<>
struct MD5Sum< ::deepracer_simulation_environment::ResetCarSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_simulation_environment::ResetCarSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::ResetCarSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_simulation_environment::ResetCarSrvResponse> should match 
// service_traits::DataType< ::deepracer_simulation_environment::ResetCarSrv > 
template<>
struct DataType< ::deepracer_simulation_environment::ResetCarSrvResponse>
{
  static const char* value()
  {
    return DataType< ::deepracer_simulation_environment::ResetCarSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::ResetCarSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_RESETCARSRV_H
